/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Reputation: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "authorized",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "educatorScore",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "increaseEducatorScore",
          inputs: [
            {
              name: "educator",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "increaseLearnerScore",
          inputs: [
            {
              name: "learner",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "learnerScore",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setAuthorized",
          inputs: [
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
            {
              name: "isAuth",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "AuthorizedUpdated",
          inputs: [
            {
              name: "contractAddr",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "isAuthorized",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EducatorScoreIncreased",
          inputs: [
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newScore",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LearnerScoreIncreased",
          inputs: [
            {
              name: "learner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newScore",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InvalidAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAuthorized",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    EducatorSubscription: {
      address: "0xa15bb66138824a1c7167f5e85b957d04dd34e468",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_reputation",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS_DENOMINATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "EDUCATOR_REPUTATION_POINTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PLATFORM_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SUBSCRIPTION_DURATION",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSubscription",
          inputs: [
            {
              name: "student",
              type: "address",
              internalType: "address",
            },
            {
              name: "educator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "expiry",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isSubscribed",
          inputs: [
            {
              name: "student",
              type: "address",
              internalType: "address",
            },
            {
              name: "educator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pausePlan",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "plans",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "monthlyPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "platformFeesCollected",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reputation",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract Reputation",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resumePlan",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMonthlyPrice",
          inputs: [
            {
              name: "price",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "subscribe",
          inputs: [
            {
              name: "educator",
              type: "address",
              internalType: "address",
            },
            {
              name: "months",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "subscriptions",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "expiry",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "PlanCreated",
          inputs: [
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "monthlyPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlanPaused",
          inputs: [
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlanResumed",
          inputs: [
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlatformFeeCollected",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlatformFeesWithdrawn",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Subscribed",
          inputs: [
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "months",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "expiry",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "amountPaid",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InsufficientPayment",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidMonths",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "NotEducator",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "PlanNotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    CourseRegistry: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "function",
          name: "courses",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "educator",
              type: "address",
              internalType: "address",
            },
            {
              name: "metadataURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createCourse",
          inputs: [
            {
              name: "metadataURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getCourse",
          inputs: [
            {
              name: "courseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "educator",
              type: "address",
              internalType: "address",
            },
            {
              name: "metadataURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextCourseId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setCourseActive",
          inputs: [
            {
              name: "courseId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CourseActiveChanged",
          inputs: [
            {
              name: "courseId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CourseCreated",
          inputs: [
            {
              name: "courseId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "metadataURI",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "CourseDoesNotExist",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyMetadataURI",
          inputs: [],
        },
        {
          type: "error",
          name: "NotCourseEducator",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    LearnToEarn: {
      address: "0x8ce361602b935680e8dec218b820ff5056beb7af",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_courseRegistry",
              type: "address",
              internalType: "address",
            },
            {
              name: "_educatorSubscription",
              type: "address",
              internalType: "address",
            },
            {
              name: "_reputation",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "EDUCATOR_POINTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "LEARNER_POINTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_SCORE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "completeCourse",
          inputs: [
            {
              name: "courseId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "score",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "courseCompleted",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "courseRegistry",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract CourseRegistry",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "educatorSubscription",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract EducatorSubscription",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasCompletedCourse",
          inputs: [
            {
              name: "student",
              type: "address",
              internalType: "address",
            },
            {
              name: "courseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reputation",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract Reputation",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "CourseCompleted",
          inputs: [
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "educator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "courseId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "score",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "learnerPoints",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "educatorPoints",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyCompleted",
          inputs: [],
        },
        {
          type: "error",
          name: "CourseNotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "NoActiveSubscription",
          inputs: [],
        },
        {
          type: "error",
          name: "ScoreTooLow",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
